### PR TITLE
Update babel and other dependencies, remove unnecesary decorators fixer logic

### LINKED ISSUE #52: Update babel and babel-parser, and fix remove decorators logic
Current babel version in plugin have inconsistent behaviour with fresh babel and @typescript-eslint/parser, when parse class properties/methods with decorators.

Expected behaviour:

> class properties/methods Node range include decorators range

Current behaviour:

> class properties/methods Node range not contains decorators range

Then, [code which remove decorators](https://github.com/bryanrsmith/eslint-plugin-sort-class-members/blob/master/src/rules/sort-class-members.js#L115), have a problem with expected babel-parser behaviour.

Expected behaviour:

> when class properties/methods Node range has decorators, we remove it together at [this code](https://github.com/bryanrsmith/eslint-plugin-sort-class-members/blob/master/src/rules/sort-class-members.js#L145)

Current behaviour:

> when class properties/methods Node range has decorators, we try remove it twice, and duplicate decorators text

### PR DESCRIPTION
**Pull request by SuperOleg39**
fix #52

### CODE REVIEW

**Comment by bryanrsmith** [comment]
Awesome! @ctwomey1 Does this look reasonable to you? All tests are passing.

**Comment by SuperOleg39** [comment]
Yes, i worried about decorators with comments, but existing tests very helped me)

**Comment by bryanrsmith** [comment]
Published as v1.7.0. Thanks!

**Comment by SuperOleg39** [comment]
😍

**Pull request merged**
