### PR TITLE
consistent identifier for private accessor

### PR DESCRIPTION
**Pull request by omfd**
The previous condition was giving inconsistent results for private properties and method. thanks

### CODE REVIEW

**Comment by omfd** [comment]
@bryanrsmith Hi this is a small fix but helps a lot in organizing the public / private properties & methods. I have tested this fix in my private project. 

_Earlier I was getting random ordering because of inconsistency in public private categorization_ 

This plugin is a life saver. thanks

**Comment by bryanrsmith** [comment]
Thanks @omfd. The checks are failing on the prettier formatting, but this change also causes a test to fail. Can you provide a failing test for the case you're trying to solve for, and a solution that passes existing tests?

**Comment by omfd** [comment]
This is the test case. I have a simple component where the variables are un-ordered. Expectation is to group them together as per certain rules and _maybe sort them later._

```
@Component({
  selector: 'app-pages',
  styleUrls: ['pages.component.scss'],
  template: `
      <router-outlet></router-outlet>
  `,
})
export class PagesComponent {
  menu = MENU_ITEMS;
  private first = 1;
  second = 2;
  public static third = 3;
  private tenth = "tenth";
}
```


Output as per the current version **1.15.2** after configuring the eslint properly. 


```
@Component({
  selector: 'app-pages',
  styleUrls: ['pages.component.scss'],
  template: `
      <router-outlet></router-outlet>
  `,
})
export class PagesComponent {
  public static third = 3;
  private first = 1;
  menu = MENU_ITEMS;
  second = 2;
  private tenth = 'tenth';
}
```



**== Now the output that I am getting as per the fix I am suggesting is this ==**

```
@Component({
  selector: 'app-pages',
  styleUrls: ['pages.component.scss'],
  template: `
      <router-outlet></router-outlet>
  `,
})
export class PagesComponent {
  public static third = 3;
  private first = 1;
  private tenth = 'tenth';
  menu = MENU_ITEMS;
  second = 2;
}
```










The issue that I noticed personally was wrong annotation for public and private else it is **brilliant** e.g. This is the output of **_getMemberInfo_** for the  **_private first = 1;_** variable in current version 


```
{
  name: 'first',
  type: 'property',
  decorators: [],
  static: false,
  async: false,
  ******************************private: false******************************,
  kind: undefined,
  propertyType: 'Literal',
  node: <ref *1> {
    type: 'PropertyDefinition',
    key: {
      type: 'Identifier',
      name: 'first',
      range: [Array],
      loc: [Object],
      parent: [Circular *1]
    },
    value: {
      type: 'Literal',
      value: 1,
      raw: '1',
      range: [Array],
      loc: [Object],
      parent: [Circular *1]
    },
    computed: false,
    static: false,
    readonly: undefined,
    declare: false,
    override: false,
    range: [ 389, 407 ],
    loc: { start: [Object], end: [Object] },
    ******************************accessibility: 'private'******************************,
    parent: {
      type: 'ClassBody',
      body: [Array],
      range: [Array],
      loc: [Object],
      parent: [Object]
    }
  }
}

```





Hope that helps. Thanks !

**Comment by bryanrsmith** [comment]
Ah, I see. I think the current private support is for ES private fields, not typescript accessibility modifiers. There’s been some discussion about this in previous issues or PRs, and I can’t remember the outcome now (sorry, on mobile and can’t search now). You might be able to find some interesting context by searching, and I can look closer tomorrow.

**Comment by omfd** [comment]
@bryanrsmith No issues man. 

That small fix to the existing code, makes it work for my angular application which is extremely life savior ;) 

I need be we can make it typescript compatible

**Comment by bryanrsmith** [comment]
@omfd I found the discussion I was thinking of in https://github.com/bryanrsmith/eslint-plugin-sort-class-members/pull/68. I went ahead and implemented support for matching on TS accessibility modifiers, published in `v1.16.0`. You should be able to define groups with something like `"accessibility": "private"`. There are a few tests with examples. Please let me know if this works for you!

**Comment by omfd** [comment]
@bryanrsmith that is great. I will update my code accordingly and let you know if there are any issues encountered. 

Effort is much appreciated. Thanks

**Pull request closed without merging**
